# Generated by Django 5.2.16 on 2026-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='Cloudinary CDN or image URL', max_length=500, null=True),
        ),
    ]
