# Generated by Django 5.2.16 on 2026-08-04 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlide',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('badge_text', models.CharField(default='CSE 303 Lab Project', max_length=100)),
                ('badge_color', models.CharField(default='primary', help_text='Bootstrap badge color e.g. primary, warning, info, success, danger', max_length=50)),
                ('button_text', models.CharField(default='Explore Products', max_length=100)),
                ('button_url', models.CharField(default='#catalog-section', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, help_text='Image URL or uploaded photo URL', max_length=500, null=True)),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, help_text='Optional linked product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='store.product')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
